# Generated by rust2rpm 10
%bcond_with check
%global debug_package %{nil}

%global crate chrono-tz

Name:           rust-%{crate}
Version:        0.5.1
Release:        2%{?dist}
Summary:        TimeZone implementations for rust-chrono from the IANA database

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/chrono-tz
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
TimeZone implementations for rust-chrono from the IANA database.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages
which use "serde" feature of "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
mkdir .tmp
mv $(grep -Po '"\Ktz/[^"]+' build.rs) .tmp
rm -rf tz
mv .tmp tz
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Nov 12 07:43:37 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.5.1-2
- Remove all unneeded files from tz

* Tue Nov 05 23:23:40 EET 2019 Artem Polishchuk <ego.cordatus@gmail.com> - 0.5.1-1
- Initial package
